// react-task-manager/src/components/FilterBar.jsx
export default function FilterBar({ filter, setFilter }) {
  const filters = ["all", "completed", "pending"];

  return (
    <div className="btn-group w-100 mb-3">
      {filters.map((f) => (
        <button
          key={f}
          className={`btn ${
            filter === f ? "btn-dark" : "btn-outline-dark"
          }`}
          onClick={() => setFilter(f)}
        >
          {f}
        </button>
      ))}
    </div>
  );
}

// angular-task-manager/src/app/components/filter-bar/filter-bar.component.ts
import { Component } from '@angular/core';
import { TaskService } from '../../services/task.service';

@Component({
  selector: 'app-filter-bar',
  templateUrl: './filter-bar.component.html'
})
export class FilterBarComponent {

  constructor(public service: TaskService) {}

  setFilter(value: string) {
    this.service.filter = value;
  }
}

<div class="btn-group w-100 mb-3">

  <button class="btn btn-outline-dark" (click)="setFilter('all')">All</button>
  <button class="btn btn-outline-dark" (click)="setFilter('completed')">Completed</button>
  <button class="btn btn-outline-dark" (click)="setFilter('pending')">Pending</button>

</div>
