// react-task-manager/src/App.jsx
import TaskForm from "./components/TaskForm";
import TaskList from "./components/TaskList";
import FilterBar from "./components/FilterBar";
import useTasks from "./hooks/useTasks";

export default function App() {
  const {
    filteredTasks,
    addTask,
    deleteTask,
    toggleTask,
    filter,
    setFilter,
  } = useTasks();

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-6">

          <div className="card shadow">
            <div className="card-body">

              <h3 className="text-center mb-4">Task Manager</h3>

              <TaskForm onAdd={addTask} />
              <FilterBar filter={filter} setFilter={setFilter} />
              <TaskList
                tasks={filteredTasks}
                onDelete={deleteTask}
                onToggle={toggleTask}
              />

            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

// angular-task-manager/src/app/app.component.ts
import { Component } from '@angular/core';
import { TaskFormComponent } from './components/task-form/task-form.component';
import { TaskListComponent } from './components/task-list/task-list.component';
import { FilterBarComponent } from './components/filter-bar/filter-bar.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    TaskFormComponent,
    TaskListComponent,
    FilterBarComponent
  ],
  templateUrl: './app.component.html'
})
export class AppComponent {}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <div class="card shadow p-4">

        <h3 class="text-center mb-3">Task Manager</h3>

        <app-task-form></app-task-form>
        <app-filter-bar></app-filter-bar>
        <app-task-list></app-task-list>

      </div>

    </div>
  </div>
</div>
