// react-task-manager/src/components/TaskItem.jsx
export default function TaskItem({ task, onDelete, onToggle }) {
  return (
    <li className="list-group-item d-flex justify-content-between align-items-center">

      <div>
        <h6
          className={task.completed ? "text-decoration-line-through" : ""}
        >
          {task.title}
        </h6>
        <small className="text-muted">{task.description}</small>
      </div>

      <div>
        <button
          className="btn btn-success btn-sm me-2"
          onClick={() => onToggle(task.id)}
        >
          ✓
        </button>

        <button
          className="btn btn-danger btn-sm"
          onClick={() => onDelete(task.id)}
        >
          ✕
        </button>
      </div>

    </li>
  );
}

// angular-task-manager/src/app/components/task-item/task-item.component.ts
import { Component, Input } from '@angular/core';
import { Task } from '../../models/task.model';
import { TaskService } from '../../services/task.service';

@Component({
  selector: 'app-task-item',
  templateUrl: './task-item.component.html'
})
export class TaskItemComponent {

  @Input() task!: Task;

  constructor(private service: TaskService) {}

  toggle() {
    this.service.toggle(this.task.id);
  }

  delete() {
    this.service.delete(this.task.id);
  }
}

<li class="list-group-item d-flex justify-content-between">

  <span [style.textDecoration]="task.completed ? 'line-through' : ''">
    {{ task.title }}
  </span>

  <div>
    <button class="btn btn-success btn-sm me-2" (click)="toggle()">✓</button>
    <button class="btn btn-danger btn-sm" (click)="delete()">✕</button>
  </div>

</li>
