// angular-task-manager/src/app/components/task-form/task-form.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TaskService } from '../../services/task.service';

@Component({
  selector: 'app-task-form',
  standalone: true,
  imports: [FormsModule], // required for [(ngModel)]
  templateUrl: './task-form.component.html'
})
export class TaskFormComponent {

  title = '';
  description = '';

  constructor(private service: TaskService) {}

  addTask() {
    if (!this.title.trim()) return;

    this.service.add(this.title, this.description);

    this.title = '';
    this.description = '';
  }
}

<div class="mb-3">

  <input
    type="text"
    class="form-control mb-2"
    placeholder="Title"
    [(ngModel)]="title"
  />

  <input
    type="text"
    class="form-control mb-2"
    placeholder="Description"
    [(ngModel)]="description"
  />

  <button
    class="btn btn-primary w-100"
    (click)="addTask()"
  >
    Add Task
  </button>

</div>

// react-task-manager/src/components/TaskForm.jsx
import { useState } from "react";

export default function TaskForm({ onAdd }) {
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");

  const submit = (e) => {
    e.preventDefault();
    if (!title) return;

    onAdd(title, desc);
    setTitle("");
    setDesc("");
  };

  return (
    <form onSubmit={submit} className="mb-3">

      <input
        className="form-control mb-2"
        placeholder="Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />

      <input
        className="form-control mb-2"
        placeholder="Description"
        value={desc}
        onChange={(e) => setDesc(e.target.value)}
      />

      <button className="btn btn-primary w-100">
        Add Task
      </button>

    </form>
  );
}
